name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: 'Unit Testing / PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }}'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0.6
      - name: Copy .env.example to .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: check where am i
        run: pwd && ls -al
      - name: Install composer dependencies
        run: composer install
      - name: Set required directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Generate encryption key
        run: php artisan key:generate
      - name: Install NPM dependencies
        run: npm i
      - name: Minify CSS and JS files
        run: npm run build
      - name: Run unit tests via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/codecept run
